version: 2.1

jobs:
  test:
    docker:
      - image: circleci/python:3.10
    steps:
      - checkout
      - run:
          name: Install uv
          command: |
            curl -sSL https://install.uv.tools | bash
      - run:
          name: Install dependencies
          command: uv init  # Installs dependencies from pyproject.toml
      - run:
          name: Run pytest tests
          command: pytest tests
      - run:
          name: Run ruff for linting
          command: ruff check .
      - run:
          name: Run mypy for type checking
          command: mypy .

workflows:
  version: 2
  test_and_static_analysis:
    jobs:
      - test
